/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Milan (https://sketchfab.com/milanfonken)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/monalisa-fa55dc4f8b7f4ac398f3aee7b5e047bc
title: Monalisa
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { PresentationControls } from "@react-three/drei/web";
import { useFrame } from "@react-three/fiber";

export function Painting(props) {
  const { nodes, materials } = useGLTF("/assets/models/painting/painting.gltf");

  return (
    <group {...props} dispose={null} position={[0.6, -4, 0]} scale={0.08}>
      <group position={[-16.99, 0, -25.55]} rotation={[-Math.PI / 2, 0, 3.14]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.49, 51.34, -9.84]} rotation={[Math.PI, 0, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.Material_27}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/painting.gltf");
